input_data_path: "data/raw/"
output_model_path: "artifacts/model_rf.pkl"
test_predictions_path: "artifacts/preds_rf.pkl"
splitting_params:
  val_size: 0.3
  random_state: 42
train_params:
  model_type: "random_forest"
  random_state: 14
  kwargs:
    n_estimators: 100
    criterion: "squared_error"
    max_depth: null
feature_params:
  categorical_policy: "ohe"
  numerical_policy: "identity"
  date_column: "datetime"
  extra_features_enabled: true
  categorical_features:
    - "season"
    - "weather"
    - "workingday"
    - "holiday"
  numerical_features:
    - "temp"
    - "atemp"
    - "windspeed"
    - "humidity"
  target_col: "count"